# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.0.2

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["terraform fmt -check"]
  terraform_version: 1.5.7

# The set of tests to run to verify your module works correctly
tests:
# this test does not work because spacelift test env does not have permission to create users.
#  - name: example-main
#    project_root: examples/main
#    environment:
#      TF_VAR_create_iam_user: true

  - name: example-main-no-iam
    project_root: examples/main
    environment:
      TF_VAR_create_iam_user: false
  